name: release_grpc_buf

on:
  release: # Docs: <https://help.github.com/en/articles/events-that-trigger-workflows#release-event-release>
    types:
      - prereleased
      - released

jobs:
  build:
    name: BSR build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          repository: 'roadrunner-server/grpc'
          ref: 'master'

      - name: Generate builder values
        id: values
        run: |
          echo "::set-output name=version::`echo ${GITHUB_REF##*/} | sed -e 's/*//'`"

      - name: Build image
        run: |
          echo ${{ secrets.BSR_TOKEN }} | docker login -u roadrunner-server plugins.buf.build --password-stdin
          docker build . -f protoc_plugins/Dockerfile -t plugins.buf.build/roadrunner/protoc-gen-php-grpc:${{ steps.values.outputs.version }} --build-arg "APP_VERSION=${{ steps.values.outputs.version }}"
          docker push plugins.buf.build/roadrunner/protoc-gen-php-grpc:${{ steps.values.outputs.version }}
